[package]
name = "r-unic/componentize"
description = "Component system"
version = "0.3.4"
license = "MIT"
authors = ["Runic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.6"
Array = "r-unic/array@0.2.3"