[package]
name = "r-unic/componentize"
description = "Component system"
version = "0.1.2"
license = "MIT"
authors = ["Runic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
janitor = "howmanysmall/janitor@1.15.6"